---
trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - .gitignore
      - screenshots
name: UdacityP3 Pipelines
variables:
  python.version: 3.9.1
stages:
  - stage: Provision
    jobs:
      - job: provision_azure_infrastructure
        displayName: Provision Azure Infrastructure
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DownloadSecureFile@1
            inputs:
              secureFile: .env
          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: 'known_host'
              sshPublicKey: '$(ssh_pub_key)' 
              sshKeySecureFile: 'id_rsa'
          - task: TerraformInstaller@0
            displayName: "Install Terraform"
            inputs:
                terraformVersion: 'latest'
          - task: TerraformCLI@0
            displayName: 'check terraform version'
            inputs:
              command: version
          
          - task: TerraformCLI@0
            displayName: 'terraform init'
            inputs:              
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendServiceArm: up3connection620
              backendAzureRmResourceGroupName: up3-storeRG360
              backendAzureRmStorageAccountName: up3store620
              backendAzureRmContainerName: up3blob620
              backendAzureRmResourceGroupLocation: centralus
              backendAzureRmKey: 'terraform.tfstate'
              allowTelemetryCollection: true

          - task: TerraformCLI@0
            displayName: 'terraform plan'
            inputs:
              command: plan
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform
              environmentServiceName: 'up3connection620'
              runAzLogin: true
              secureVarsFile: 'terraform.tfvars'
              allowTelemetryCollection: true

          - task: TerraformCLI@0
            displayName: 'terraform apply'
            inputs:
              command: apply
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform
              environmentServiceName: 'up3connection620'
              runAzLogin: true
              backendServiceArm: up3connection620
              backendAzureRmResourceGroupName: up3-storeRG360
              backendAzureRmStorageAccountName: up3store620
              backendAzureRmContainerName: up3blob620
              backendAzureRmResourceGroupLocation: centralus
              backendAzureRmKey: 'terraform.tfstate'
              allowTelemetryCollection: true
        