---
trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - .gitignore
      - screenshots
name: UdacityP3 Pipelines
variables:
  python.version: 3.9.1
stages:
  - stage: Provision
    jobs:
      - job: provision_azure_infrastructure
        displayName: Provision Azure Infrastructure
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DownloadSecureFile@1
            inputs:
              secureFile: .env
          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: 'known_host'
              sshPublicKey: '$(ssh_pub_key)' 
              sshKeySecureFile: 'id_rsa'
          - task: Bash@3
            displayName: 'Delete Terraform files from previous run'
            inputs:
              targetType: 'inline'
              script: |
                cd $(System.DefaultWorkingDirectory)/terraform
                rm -rf .terraform
                rm -rf .terraform.lock.hcl
          - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
            displayName: 'Use Terraform latest'
            inputs:
                workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'    
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: latest
          - task: TerraformCLI@0
            displayName: 'terraform init'
            inputs:
              command: init
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform
              secureVarsFile: '.env'
              backendType: azurerm
              backendServiceArm: UdacityP3_storage
              ensureBackend: true
              backendAzureRmResourceGroupName: udacityP3-RG
              backendAzureRmResourceGroupLocation: centralus
              backendAzureRmStorageAccountName: udacityp3storageacct
              backendAzureRmContainerName: udacityp3blobcontain
              backendAzureRmKey: 'terraform.tfstate'
              allowTelemetryCollection: false
          - task: TerraformCLI@0
            inputs:
              command: 'import'
              environmentServiceName: 'Udacity Devops P3(25283872-c0f5-4f2e-9c2a-f19f8e24b3c4)'
              runAzLogin: true
              allowTelemetryCollection: true
              resourceAddress: 'module.resource_group.azurerm_resource_group.test'
              resourceId: '/subscriptions/25283872-c0f5-4f2e-9c2a-f19f8e24b3c4/resourceGroups/udacityp3-RG'
          - task: TerraformCLI@0
            displayName: 'terraform plan'
            inputs:
              command: plan
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform
              environmentServiceName: UdacityP3_storage
              runAzLogin: true
              secureVarsFile: 'terraform.tfvars'
          - task: TerraformCLI@0
            displayName: 'terraform apply'
            inputs:
              command: apply
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform
              environmentServiceName: UdacityP3_storage
              runAzLogin: true
              secureVarsFile: 'terraform.tfvars'
              commandOptions: '-auto-approve'
              allowTelemetryCollection: true
        