# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#trigger pipeline
trigger:
  branches:
    include:
      - master
  
  paths:
    exclude:
    -  README.md
    - .gitignore
    - screenshots
name: UdacityP3 Pipelines
variables:
  python.version: '3.9.1'
stages:
- stage: Provision
  jobs:
  - job: provision_azure_infrastructure
    displayName: Provision Azure Infrastructure
    pool:
      vmImage: 'ubuntu-latest'
    steps:    
    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'terraform.tfvars'
    
    # Needed for Terraform VM deployment
    # - task: InstallSSHKey@0
    #   inputs:
    #     knownHostsEntry: 'KNOWN_HOSTS_STRING'
    #     sshPublicKey: 'PUBLIC_KEY'
    #     sshKeySecureFile: 'id_rsa'
    #
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: 'known_host'
        sshPublicKey: 'PUBLIC_KEY'
        sshKeySecureFile: 'id_rsa.pub'
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

 #-------Terraform Deployment Resources----------------------
    - task: TerraformCLI@0
      inputs:
        command: 'init'
        secureVarsFile: 'terraform.tfvars'
        backendType: 'azurerm'
        backendServiceArm: 'Resource Group'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'udacityp3-RG'
        backendAzureRmStorageAccountName: 'udacitystorageacct'
        backendAzureRmContainerName: 'udacityp3-blobcontain'
        backendAzureRmKey: 'gCYcel4/8pvkzR2jnILtTyH+cUUrPPnhmu704dJwDF1bdSGdFA+F+bXv36prVzyNDg6TiHxB6Qh3inIF43VdFA=='
        allowTelemetryCollection: false


    

    # - deployment: VMDeploy
  #   displayName: NAME
  #   environment:
  #     name:  ENVIRONMENT NAME
  #     resourceType: VirtualMachine
  #     tags: TAG NAME
  #   strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - task: Bash@3
  #           inputs:
  #             targetType: 'inline'
  #             script: |
  #               #! /bin/bash
  
  # -------resources for Terraform ------------------
  

    #--------- Postman/Newman---------------
    #---------Selenium----------------------
    #---------Installing Log Agents---------
    #---------Jmeter------------------------
    #---------Destroy project---------------

  
                
  #               sudo apt-get upgrade -y
  #               sudo apt-get install python3-pip -y
  #               sudo apt-get install unzip -y
  #               sudo apt-get install -y chromium-browser
  #               pip3 install selenium
  #               export PATH=$PATH:some/path


